/***********************************************************************************************************************
 *
 * Unity-SCORM Integration Toolkit Version 1.0 Beta
 * ==========================================
 *
 * Copyright (C) 2011, by ADL (Advance Distributed Learning). (http://www.adlnet.gov)
 * http://www.adlnet.gov/UnityScormIntegration/
 *
 ***********************************************************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 **********************************************************************************************************************/

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using ScormSerialization;
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace Scorm2004
{

    public partial class DataModel
    {

        public DataModel()
        {
            this.comments_from_learner = new System.Collections.Generic.List<commentType>();
            this.comments_from_lms = new System.Collections.Generic.List<commentType>();
            this.interactions = new System.Collections.Generic.List<interactionType>();
            this.learner_preference = new learnerPreferenceType();
            this.objectives = new System.Collections.Generic.List<objectiveType>();
            this.score = new scoreType();
        }

        private System.Collections.Generic.List<commentType> commentsFromLearnerField;

        private System.Collections.Generic.List<commentType> commentsFromLMSField;

        private completionStatusType completionStatusField;

        private bool completionStatusFieldSpecified;

        private decimal completionThresholdField;

        private bool completionThresholdFieldSpecified;

        [ScormSerialization.ReadOnly]
        private credit creditField;

        private bool creditFieldSpecified;

        [IgnoreAttribute]
        private string dataModelVersionField;

        [ScormSerialization.ReadOnly]
        private entry entryField;

        private bool entryFieldSpecified;

        [ScormSerialization.WriteOnly]
        private exit exitField;

        private bool exitFieldSpecified;

        private System.Collections.Generic.List<interactionType> interactionsField;
        [ScormSerialization.ReadOnly]
        private string launchDataField;
        [ScormSerialization.ReadOnly]
        private string learnerIdField;
        [ScormSerialization.ReadOnly]
        private learnerName learnerNameField;
        [ScormSerialization.ReadOnly]
        private learnerPreferenceType learnerPreferenceField;

        private string locationField;
        [ScormSerialization.ReadOnly]
        private TimeSpan maxTimeAllowedField;
        [ScormSerialization.ReadOnly]
        private mode modeField;

        private bool modeFieldSpecified;

        private System.Collections.Generic.List<objectiveType> objectivesField;

        private System.Nullable<decimal> progressMeasureField;

        private bool progressMeasureFieldSpecified;

        private System.Nullable<decimal> scaledPassingScoreField;

        private bool scaledPassingScoreFieldSpecified;

        private scoreType scoreField;

        [ScormSerialization.WriteOnly]
        private TimeSpan sessionTimeField;

        private successStatusType successStatusField;

        private bool successStatusFieldSpecified;

        private string suspendDataField;
        [ScormSerialization.ReadOnly]
        private timeLimitAction timeLimitActionField;

        private bool timeLimitActionFieldSpecified;
        [ScormSerialization.ReadOnly]
        private TimeSpan totalTimeField;
        [ScormSerialization.ReadOnly]
        private int attemptNumberField;

        private bool attemptNumberFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commentFromLearner", IsNullable = false)]
        public System.Collections.Generic.List<commentType> comments_from_learner
        {
            get
            {
                return this.commentsFromLearnerField;
            }
            set
            {
                this.commentsFromLearnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commentFromLMS", IsNullable = false)]
        public System.Collections.Generic.List<commentType> comments_from_lms
        {
            get
            {
                return this.commentsFromLMSField;
            }
            set
            {
                this.commentsFromLMSField = value;
            }
        }

        /// <remarks/>
        public completionStatusType completion_status
        {
            get
            {
                return this.completionStatusField;
            }
            set
            {
                this.completionStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool completionStatusSpecified
        {
            get
            {
                return this.completionStatusFieldSpecified;
            }
            set
            {
                this.completionStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public decimal completion_threshold
        {
            get
            {
                return this.completionThresholdField;
            }
            set
            {
                this.completionThresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool completionThresholdSpecified
        {
            get
            {
                return this.completionThresholdFieldSpecified;
            }
            set
            {
                this.completionThresholdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public credit credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool creditSpecified
        {
            get
            {
                return this.creditFieldSpecified;
            }
            set
            {
                this.creditFieldSpecified = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.Ignore]
        public string dataModelVersion
        {
            get
            {
                return this.dataModelVersionField;
            }
            set
            {
                this.dataModelVersionField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public entry entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool entrySpecified
        {
            get
            {
                return this.entryFieldSpecified;
            }
            set
            {
                this.entryFieldSpecified = value;
            }
        }

        [ScormSerialization.WriteOnly]
        /// <remarks/>
        public exit exit
        {
            get
            {
                return this.exitField;
            }
            set
            {
                this.exitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool exitSpecified
        {
            get
            {
                return this.exitFieldSpecified;
            }
            set
            {
                this.exitFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("interaction", IsNullable = false)]
        public System.Collections.Generic.List<interactionType> interactions
        {
            get
            {
                return this.interactionsField;
            }
            set
            {
                this.interactionsField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public string launch_data
        {
            get
            {
                return this.launchDataField;
            }
            set
            {
                this.launchDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        [ScormSerialization.ReadOnly]
        public string learner_id
        {
            get
            {
                return this.learnerIdField;
            }
            set
            {
                this.learnerIdField = value;
            }
        }

        [ScormSerialization.ReadOnly]
        /// <remarks/>
        public learnerName learner_name
        {
            get
            {
                return this.learnerNameField;
            }
            set
            {
                this.learnerNameField = value;
            }
        }

        /// <remarks/>
        public learnerPreferenceType learner_preference
        {
            get
            {
                return this.learnerPreferenceField;
            }
            set
            {
                this.learnerPreferenceField = value;
            }
        }

        /// <remarks/>
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        [ScormSerialization.ReadOnly]
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public TimeSpan max_time_allowed
        {
            get
            {
                return this.maxTimeAllowedField;
            }
            set
            {
                this.maxTimeAllowedField = value;
            }
        }

        [ScormSerialization.ReadOnly]
        /// <remarks/>
        public mode mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool modeSpecified
        {
            get
            {
                return this.modeFieldSpecified;
            }
            set
            {
                this.modeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objective", IsNullable = false)]
        public System.Collections.Generic.List<objectiveType> objectives
        {
            get
            {
                return this.objectivesField;
            }
            set
            {
                this.objectivesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> progress_measure
        {
            get
            {
                return this.progressMeasureField;
            }
            set
            {
                this.progressMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool progressMeasureSpecified
        {
            get
            {
                return this.progressMeasureFieldSpecified;
            }
            set
            {
                this.progressMeasureFieldSpecified = value;
            }
        }

        [ScormSerialization.ReadOnly]
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> scaled_passing_score
        {
            get
            {
                return this.scaledPassingScoreField;
            }
            set
            {
                this.scaledPassingScoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool scaledPassingScoreSpecified
        {
            get
            {
                return this.scaledPassingScoreFieldSpecified;
            }
            set
            {
                this.scaledPassingScoreFieldSpecified = value;
            }
        }
        [ScormSerialization.WriteOnly]
        public scoreType score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }
        [ScormSerialization.WriteOnly]
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public TimeSpan session_time
        {
            get
            {
                return this.sessionTimeField;
            }
            set
            {
                this.sessionTimeField = value;
            }
        }

        /// <remarks/>
        public successStatusType success_status
        {
            get
            {
                return this.successStatusField;
            }
            set
            {
                this.successStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool successStatusSpecified
        {
            get
            {
                return this.successStatusFieldSpecified;
            }
            set
            {
                this.successStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string suspend_data
        {
            get
            {
                return this.suspendDataField;
            }
            set
            {
                this.suspendDataField = value;
            }
        }
        [ScormSerialization.ReadOnly]
        /// <remarks/>
        public timeLimitAction time_limit_action
        {
            get
            {
                return this.timeLimitActionField;
            }
            set
            {
                this.timeLimitActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool timeLimitActionSpecified
        {
            get
            {
                return this.timeLimitActionFieldSpecified;
            }
            set
            {
                this.timeLimitActionFieldSpecified = value;
            }
        }

        [ScormSerialization.ReadOnly]
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public TimeSpan total_time
        {
            get
            {
                return this.totalTimeField;
            }
            set
            {
                this.totalTimeField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.Ignore]
        public int attemptNumber
        {
            get
            {
                return this.attemptNumberField;
            }
            set
            {
                this.attemptNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool attemptNumberSpecified
        {
            get
            {
                return this.attemptNumberFieldSpecified;
            }
            set
            {
                this.attemptNumberFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class commentType
    {
        public commentType()
        {
            this.comment = new commentTypeComment();
            this.timestamp = new Scorm2004.DateTime(System.DateTime.Now);

        }
        private commentTypeComment commentField;

        private string locationField;

        private Scorm2004.DateTime timeStampField;

        private bool timeStampFieldSpecified;

        private string identifierField;

        /// <remarks/>
        public commentTypeComment comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public Scorm2004.DateTime timestamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool timeStampSpecified
        {
            get
            {
                return this.timeStampFieldSpecified;
            }
            set
            {
                this.timeStampFieldSpecified = value;
            }
        }

        [ScormSerialization.Ignore]
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string id
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class scoreType
    {

        private System.Nullable<decimal> scaledField;

        private bool scaledFieldSpecified;

        private System.Nullable<decimal> rawField;

        private bool rawFieldSpecified;

        private System.Nullable<decimal> minField;

        private bool minFieldSpecified;

        private System.Nullable<decimal> maxField;

        private bool maxFieldSpecified;

        /// <remarks/>
        public System.Nullable<decimal> scaled
        {
            get
            {
                return this.scaledField;
            }
            set
            {
                this.scaledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool scaledSpecified
        {
            get
            {
                return this.scaledFieldSpecified;
            }
            set
            {
                this.scaledFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.Nullable<decimal> raw
        {
            get
            {
                return this.rawField;
            }
            set
            {
                this.rawField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool rawSpecified
        {
            get
            {
                return this.rawFieldSpecified;
            }
            set
            {
                this.rawFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.Nullable<decimal> min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool minSpecified
        {
            get
            {
                return this.minFieldSpecified;
            }
            set
            {
                this.minFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.Nullable<decimal> max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool maxSpecified
        {
            get
            {
                return this.maxFieldSpecified;
            }
            set
            {
                this.maxFieldSpecified = value;
            }
        }

    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerPreferenceType
    {

        private System.Nullable<Decimal> audioLevelField;

        private bool audioLevelFieldSpecified;

        private string languageField;

        private System.Nullable<decimal> deliverySpeedField;

        private bool deliverySpeedFieldSpecified;

        private learnerPreferenceAudioCaptioning audioCaptioningField;

        private bool audioCaptioningFieldSpecified;


        /// <remarks/>
        public System.Nullable<Decimal> audio_level
        {
            get
            {
                return this.audioLevelField;
            }
            set
            {
                this.audioLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool audioLevelSpecified
        {
            get
            {
                return this.audioLevelFieldSpecified;
            }
            set
            {
                this.audioLevelFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public System.Nullable<decimal> delivery_speed
        {
            get
            {
                return this.deliverySpeedField;
            }
            set
            {
                this.deliverySpeedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool deliverySpeedSpecified
        {
            get
            {
                return this.deliverySpeedFieldSpecified;
            }
            set
            {
                this.deliverySpeedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public learnerPreferenceAudioCaptioning audio_captioning
        {
            get
            {
                return this.audioCaptioningField;
            }
            set
            {
                this.audioCaptioningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool audioCaptioningSpecified
        {
            get
            {
                return this.audioCaptioningFieldSpecified;
            }
            set
            {
                this.audioCaptioningFieldSpecified = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class commentTypeComment
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class objectiveType
    {

        public objectiveType()
        {
            this.completion_status = completionStatusType.not_attempted;
            this.description = new objectiveTypeDescription();
            this.score = new scoreType();

        }
        private string identifierField;

        private scoreType scoreField;

        private System.Nullable<decimal> progressMeasureField;

        private bool progressMeasureFieldSpecified;

        private completionStatusType completionStatusField;

        private bool completionStatusFieldSpecified;

        private successStatusType successStatusField;

        private bool successStatusFieldSpecified;

        private objectiveTypeDescription descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        [Priority(0)]
        public string id
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        [ScormSerialization.WriteOnly]
        public scoreType score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> progress_measure
        {
            get
            {
                return this.progressMeasureField;
            }
            set
            {
                this.progressMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool progressMeasureSpecified
        {
            get
            {
                return this.progressMeasureFieldSpecified;
            }
            set
            {
                this.progressMeasureFieldSpecified = value;
            }
        }

        /// <remarks/>
        public completionStatusType completion_status
        {
            get
            {
                return this.completionStatusField;
            }
            set
            {
                this.completionStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool completionStatusSpecified
        {
            get
            {
                return this.completionStatusFieldSpecified;
            }
            set
            {
                this.completionStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public successStatusType success_status
        {
            get
            {
                return this.successStatusField;
            }
            set
            {
                this.successStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool successStatusSpecified
        {
            get
            {
                return this.successStatusFieldSpecified;
            }
            set
            {
                this.successStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public objectiveTypeDescription description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum completionStatusType
    {

        not_set,
        /// <remarks/>
        completed,

        /// <remarks/>
        incomplete,

        /// <remarks/>
        not_attempted,

        /// <remarks/>
        unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum successStatusType
    {
        not_set,
        /// <remarks/>
        failed,

        /// <remarks/>
        passed,

        /// <remarks/>
        unknown,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class objectiveTypeDescription
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseType
    {


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponseFillIn : learnerResponseType
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponseLongFillIn : learnerResponseType
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponseMatching : learnerResponseType
    {

        private System.Collections.Generic.List<learnerResponseTypeLearnerResponseMatchingMatch> matchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public System.Collections.Generic.List<learnerResponseTypeLearnerResponseMatchingMatch> match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponseMatchingMatch : learnerResponseType
    {

        private string sourceField;

        private string targetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponseMultipleChoice : learnerResponseType
    {

        private System.Collections.Generic.List<string> choiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("choice", DataType = "anyURI")]
        public System.Collections.Generic.List<string> choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponsePerformance : learnerResponseType
    {

        private string stepNameField;

        private learnerResponseTypeLearnerResponsePerformanceStepAnswer stepAnswerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string stepName
        {
            get
            {
                return this.stepNameField;
            }
            set
            {
                this.stepNameField = value;
            }
        }

        /// <remarks/>
        public learnerResponseTypeLearnerResponsePerformanceStepAnswer stepAnswer
        {
            get
            {
                return this.stepAnswerField;
            }
            set
            {
                this.stepAnswerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponsePerformanceStepAnswer : learnerResponseType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("literal", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("numeric", typeof(decimal))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerResponseTypeLearnerResponseSequencing : learnerResponseType
    {

        private System.Collections.Generic.List<string> stepField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step", DataType = "anyURI")]
        public System.Collections.Generic.List<string> step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {
        not_set,
        /// <remarks/>
        learnerResponseFillIn,

        /// <remarks/>
        learnerResponseLikert,

        /// <remarks/>
        learnerResponseLongFillIn,

        /// <remarks/>
        learnerResponseMatching,

        /// <remarks/>
        learnerResponseMultipleChoice,

        /// <remarks/>
        learnerResponseNumeric,

        /// <remarks/>
        learnerResponseOther,

        /// <remarks/>
        learnerResponsePerformance,

        /// <remarks/>
        learnerResponseSequencing,

        /// <remarks/>
        learnerResponseTrueFalse,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesType
    {
        public correctResponsesType()
        {
            this.Items = new System.Collections.Generic.List<object>();
            this.ItemsElementName = new System.Collections.Generic.List<ItemsChoiceType>();

        }
        private System.Collections.Generic.List<object> itemsField;

        private System.Collections.Generic.List<ItemsChoiceType> itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("correctResponseFillIn", typeof(correctResponsesTypeCorrectResponseFillIn))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseLikert", typeof(string), DataType = "anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseLongFillIn", typeof(correctResponsesTypeCorrectResponseLongFillIn))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseMatching", typeof(correctResponsesTypeCorrectResponseMatching))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseMultipleChoice", typeof(correctResponsesTypeCorrectResponseMultipleChoice))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseNumeric", typeof(correctResponsesTypeCorrectResponseNumeric))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseOther", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponsePerformance", typeof(correctResponsesTypeCorrectResponsePerformance))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseSequencing", typeof(correctResponsesTypeCorrectResponseSequencing))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseTrueFalse", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<ItemsChoiceType> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseFillIn
    {

        private System.Collections.Generic.List<correctResponsesTypeCorrectResponseFillInMatchText> matchTextField;

        private bool caseMattersField;

        private bool orderMattersField;

        public correctResponsesTypeCorrectResponseFillIn()
        {
            this.caseMattersField = false;
            this.orderMattersField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("matchText")]
        public System.Collections.Generic.List<correctResponsesTypeCorrectResponseFillInMatchText> matchText
        {
            get
            {
                return this.matchTextField;
            }
            set
            {
                this.matchTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool caseMatters
        {
            get
            {
                return this.caseMattersField;
            }
            set
            {
                this.caseMattersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool orderMatters
        {
            get
            {
                return this.orderMattersField;
            }
            set
            {
                this.orderMattersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseFillInMatchText
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseLongFillIn
    {

        private string langField;

        private bool caseMattersField;

        private string valueField;

        public correctResponsesTypeCorrectResponseLongFillIn()
        {
            this.caseMattersField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool caseMatters
        {
            get
            {
                return this.caseMattersField;
            }
            set
            {
                this.caseMattersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseMatching
    {

        private System.Collections.Generic.List<correctResponsesTypeCorrectResponseMatchingMatch> matchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public System.Collections.Generic.List<correctResponsesTypeCorrectResponseMatchingMatch> match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseMatchingMatch
    {

        private string sourceField;

        private string targetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseMultipleChoice
    {

        private System.Collections.Generic.List<string> choiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("choice", DataType = "anyURI")]
        public System.Collections.Generic.List<string> choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseNumeric
    {

        private decimal minField;

        private bool minFieldSpecified;

        private decimal maxField;

        private bool maxFieldSpecified;

        /// <remarks/>
        public decimal min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool minSpecified
        {
            get
            {
                return this.minFieldSpecified;
            }
            set
            {
                this.minFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool maxSpecified
        {
            get
            {
                return this.maxFieldSpecified;
            }
            set
            {
                this.maxFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformance
    {

        private System.Collections.Generic.List<correctResponsesTypeCorrectResponsePerformanceStep> stepField;

        private bool orderMattersField;

        public correctResponsesTypeCorrectResponsePerformance()
        {
            this.orderMattersField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step")]
        public System.Collections.Generic.List<correctResponsesTypeCorrectResponsePerformanceStep> step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool orderMatters
        {
            get
            {
                return this.orderMattersField;
            }
            set
            {
                this.orderMattersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformanceStep
    {

        private string stepNameField;

        private correctResponsesTypeCorrectResponsePerformanceStepStepAnswer stepAnswerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string stepName
        {
            get
            {
                return this.stepNameField;
            }
            set
            {
                this.stepNameField = value;
            }
        }

        /// <remarks/>
        public correctResponsesTypeCorrectResponsePerformanceStepStepAnswer stepAnswer
        {
            get
            {
                return this.stepAnswerField;
            }
            set
            {
                this.stepAnswerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformanceStepStepAnswer
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("literal", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("numeric", typeof(correctResponsesTypeCorrectResponsePerformanceStepStepAnswerNumeric))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformanceStepStepAnswerNumeric
    {

        private decimal minField;

        private bool minFieldSpecified;

        private decimal maxField;

        private bool maxFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool minSpecified
        {
            get
            {
                return this.minFieldSpecified;
            }
            set
            {
                this.minFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool maxSpecified
        {
            get
            {
                return this.maxFieldSpecified;
            }
            set
            {
                this.maxFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseSequencing
    {

        private System.Collections.Generic.List<string> stepField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step", DataType = "anyURI")]
        public System.Collections.Generic.List<string> step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        not_set,
        /// <remarks/>
        correctResponseFillIn,

        /// <remarks/>
        correctResponseLikert,

        /// <remarks/>
        correctResponseLongFillIn,

        /// <remarks/>
        correctResponseMatching,

        /// <remarks/>
        correctResponseMultipleChoice,

        /// <remarks/>
        correctResponseNumeric,

        /// <remarks/>
        correctResponseOther,

        /// <remarks/>
        correctResponsePerformance,

        /// <remarks/>
        correctResponseSequencing,

        /// <remarks/>
        correctResponseTrueFalse,
    }
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public class objectiveIDType
    {
        public objectiveIDType()
        {
            id = "";
        }
        public objectiveIDType(string i)
        {
            id = i;
        }
        private string _id;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class interactionType
    {

        public interactionType()
        {
            this.correct_responses = new correctResponsesType();
            this.description = new interactionTypeDescription();
            this.learner_response = new learnerResponseType();
            this.objectives = new System.Collections.Generic.List<objectiveIDType>();
            this.timestamp = new Scorm2004.DateTime(System.DateTime.Now);
            this.type = interactionTypeType.not_set;
            this.attemptNumberField = 1;
        }

        private string identifierField;

        private interactionTypeType typeField;

        private System.Collections.Generic.List<objectiveIDType> objectiveIdsField;

        private Scorm2004.DateTime timeStampField;

        private bool timeStampFieldSpecified;

        private correctResponsesType correctResponsesField;

        private System.Nullable<decimal> weightingField;

        private bool weightingFieldSpecified;

        private learnerResponseType learnerResponseField;

        private interactionTypeResult resultField;

        private bool resultFieldSpecified;

        private System.Nullable<decimal> resultNumericField;

        private bool resultNumericFieldSpecified;

        private string latencyField;

        private interactionTypeDescription descriptionField;

        private int attemptNumberField;



        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        [Priority(0)]
        public string id
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        [Priority(1)]
        /// <remarks/>
        public interactionTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objectiveId", IsNullable = false)]
        public System.Collections.Generic.List<objectiveIDType> objectives
        {
            get
            {
                return this.objectiveIdsField;
            }
            set
            {
                this.objectiveIdsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Scorm2004.DateTime timestamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool timeStampSpecified
        {
            get
            {
                return this.timeStampFieldSpecified;
            }
            set
            {
                this.timeStampFieldSpecified = value;
            }
        }

        /// <remarks/>
        public correctResponsesType correct_responses
        {
            get
            {
                return this.correctResponsesField;
            }
            set
            {
                this.correctResponsesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> weighting
        {
            get
            {
                return this.weightingField;
            }
            set
            {
                this.weightingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool weightingSpecified
        {
            get
            {
                return this.weightingFieldSpecified;
            }
            set
            {
                this.weightingFieldSpecified = value;
            }
        }

        /// <remarks/>
        public learnerResponseType learner_response
        {
            get
            {
                return this.learnerResponseField;
            }
            set
            {
                this.learnerResponseField = value;
            }
        }

        /// <remarks/>
        public interactionTypeResult result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool resultSpecified
        {
            get
            {
                return this.resultFieldSpecified;
            }
            set
            {
                this.resultFieldSpecified = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string latency
        {
            get
            {
                return this.latencyField;
            }
            set
            {
                this.latencyField = value;
            }
        }

        /// <remarks/>
        public interactionTypeDescription description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(1)]
        [ScormSerialization.Ignore]
        public int attemptNumber
        {
            get
            {
                return this.attemptNumberField;
            }
            set
            {
                this.attemptNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum interactionTypeType
    {
        not_set,
        /// <remarks/>
        true_false,

        /// <remarks/>
        multiple_choice,

        /// <remarks/>
        fill_in,

        /// <remarks/>
        long_fill_in,

        /// <remarks/>
        likert,

        /// <remarks/>
        matching,

        /// <remarks/>
        performance,

        /// <remarks/>
        sequencing,

        /// <remarks/>
        numeric,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum interactionTypeResult
    {
        not_set,
        /// <remarks/>
        correct,

        /// <remarks/>
        incorrect,

        /// <remarks/>
        neutral,

        /// <remarks/>
        unanticipated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class interactionTypeDescription
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum credit
    {
        not_set,
        /// <remarks/>
        credit,

        /// <remarks/>
        no_credit,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum entry
    {
        not_set,
        /// <remarks/>
        ab_initio,

        /// <remarks/>
        resume,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum exit
    {
        not_set,
        /// <remarks/>
        logout,

        /// <remarks/>
        normal,

        /// <remarks/>
        suspend,

        /// <remarks/>
        timeout,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class learnerName
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum learnerPreferenceAudioCaptioning
    {
        not_set,
        /// <remarks/>
        off,

        /// <remarks/>
        no_change,

        /// <remarks/>
        on,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum mode
    {
        not_set,
        /// <remarks/>
        browse,

        /// <remarks/>
        normal,

        /// <remarks/>
        review,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum timeLimitAction
    {
        not_set,
        /// <remarks/>
        continue_message,

        /// <remarks/>
        continue_no_message,

        /// <remarks/>
        exit_message,

        /// <remarks/>
        exit_no_message,
    }

  
}