/***********************************************************************************************************************
 *
 * Unity-SCORM Integration Toolkit Version 1.0 Beta
 * ==========================================
 *
 * Copyright (C) 2011, by ADL (Advance Distributed Learning). (http://www.adlnet.gov)
 * http://www.adlnet.gov/UnityScormIntegration/
 *
 ***********************************************************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 **********************************************************************************************************************/

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using ScormSerialization;
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace Scorm1_2
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://letsi.org/rte/1.0")]
    public partial class Set
    {

        private Scorm1_2.DataModel cocdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
        public Scorm1_2.DataModel cocd
        {
            get
            {
                return this.cocdField;
            }
            set
            {
                this.cocdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]

    public partial class DataModel
    {

        public DataModel()
        {
            
            this.comments = "";
            this.comments_from_lms = "";
            this.interactions = new System.Collections.Generic.List<interactionType>();
            this.student_preference = new studentPreferenceType();
            this.objectives = new System.Collections.Generic.List<objectiveType>();
        }

        private coreType coreField;

        private studentDataType studentDataField;

        private string commentsField;

        private string commentsFromLMSField;
       
        private System.Collections.Generic.List<interactionType> interactionsField;
        
        [ScormSerialization.ReadOnly]
        private string launchDataField;        
     
        [ScormSerialization.ReadOnly]
        private studentPreferenceType studentPreferenceField;
               
        private System.Collections.Generic.List<objectiveType> objectivesField;
       
        private string suspendDataField;
          
        [ScormSerialization.ReadOnly]
        private int attemptNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("core", IsNullable = false)]
        public coreType core
        {
            get
            {
                return this.coreField;
            }
            set
            {
                this.coreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("core", IsNullable = false)]
        public studentDataType student_data
        {
            get
            {
                return this.studentDataField;
            }
            set
            {
                this.studentDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("comments", IsNullable = false)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commentFromLMS", IsNullable = false)]
        [ScormSerialization.ReadOnly]
        public String comments_from_lms
        {
            get
            {
                return this.commentsFromLMSField;
            }
            set
            {
                this.commentsFromLMSField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("interaction", IsNullable = false)]
        public System.Collections.Generic.List<interactionType> interactions
        {
            get
            {
                return this.interactionsField;
            }
            set
            {
                this.interactionsField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public string launch_data
        {
            get
            {
                return this.launchDataField;
            }
            set
            {
                this.launchDataField = value;
            }
        }

        /// <remarks/>
        public studentPreferenceType student_preference
        {
            get
            {
                return this.studentPreferenceField;
            }
            set
            {
                this.studentPreferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objective", IsNullable = false)]
        public System.Collections.Generic.List<objectiveType> objectives
        {
            get
            {
                return this.objectivesField;
            }
            set
            {
                this.objectivesField = value;
            }
        }

        /// <remarks/>
        public string suspend_data
        {
            get
            {
                return this.suspendDataField;
            }
            set
            {
                this.suspendDataField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.Ignore]
        public int attemptNumber
        {
            get
            {
                return this.attemptNumberField;
            }
            set
            {
                this.attemptNumberField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class coreType
    {
        public coreType()
        {
            // jp todo: constructor ok?
            this.credit = credit.credit;
            this.lesson_status = lessonStatusType.not_attempted;
            this.entry = entry.ab_initio;
            this.score = new scoreType();
            this.lesson_mode = mode.normal; 
        }

        private string studentIDField;

        private string studentNameField;

        private string lessonLocationField;

        private credit creditField;

        private lessonStatusType lessonStatusField;

        private entry entryField;

        private scoreType scoreField;

        private Scorm1_2.TimeSpan totalTimeField;

        private mode lessonModeField;

        private exit exitField;

        private Scorm1_2.TimeSpan sessionTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        [ScormSerialization.ReadOnly]
        public string student_id
        {
            get
            {
                return this.studentIDField;
            }
            set
            {
                this.studentIDField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public string student_name
        {
            get
            {
                return this.studentNameField;
            }
            set
            {
                this.studentNameField = value;
            }
        }

        /// <remarks/>
        public string lesson_location
        {
            get
            {
                return this.lessonLocationField;
            }
            set
            {
                this.lessonLocationField = value;
            }
        }

        [ScormSerialization.ReadOnly]
        /// <remarks/>
        public credit credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField= value;
            }
        }

        /// <remarks/>
        public lessonStatusType lesson_status
        {
            get
            {
                return this.lessonStatusField;
            }
            set
            {
                this.lessonStatusField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public entry entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }

        
        public scoreType score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        [ScormSerialization.ReadOnly]
        public Scorm1_2.TimeSpan total_time
        {
            get
            {
                return this.totalTimeField;
            }
            set
            {
                this.totalTimeField = value;
            }
        }

        /// <remarks/>
        /// 
        [ScormSerialization.ReadOnly]
        public mode lesson_mode
        {
            get
            {
                return this.lessonModeField;
            }
            set
            {
                this.lessonModeField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.WriteOnly]
        public exit exit
        {
            get
            {
                return this.exitField;
            }
            set
            {
                this.exitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        [ScormSerialization.WriteOnly]
        public Scorm1_2.TimeSpan session_time
        {
            get
            {
                return this.sessionTimeField;
            }
            set
            {
                this.sessionTimeField = value;
            }
        }

    }





    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentDataType
    {

        private System.Nullable<decimal> masteryScoreField;

        private Scorm1_2.TimeSpan maxTimeAllowedField;

        private timeLimitAction timeLimitActionField;

        public System.Nullable<decimal> mastery_score
        {
            get
            {
                return this.masteryScoreField;
            }
            set
            {
                this.masteryScoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        [ScormSerialization.ReadOnly]
        public Scorm1_2.TimeSpan max_time_allowed
        {
            get
            {
                return this.maxTimeAllowedField;
            }
            set
            {
                this.maxTimeAllowedField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.ReadOnly]
        public timeLimitAction time_limit_action
        {
            get
            {
                return this.timeLimitActionField;
            }
            set
            {
                this.timeLimitActionField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class scoreType
    {

        private System.Nullable<decimal> rawField;

        private System.Nullable<decimal> minField;

        private System.Nullable<decimal> maxField;

        /// <remarks/>
        /// 
        [ScormSerialization.WriteOnly]
        public System.Nullable<decimal> raw
        {
            get
            {
                return this.rawField;
            }
            set
            {
                this.rawField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.WriteOnly]
        public System.Nullable<decimal> min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [ScormSerialization.WriteOnly]
        public System.Nullable<decimal> max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentPreferenceType
    {

        private System.Nullable<decimal> audioField;

        private string languageField;

        private System.Nullable<decimal> speedField;

        private learnerPreferenceAudioCaptioning textField;

        /// <remarks/>
        public System.Nullable<decimal> audio
        {
            get
            {
                return this.audioField;
            }
            set
            {
                this.audioField = value;
            }
        }

        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public System.Nullable<decimal> speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }

        /// <remarks/>
        public learnerPreferenceAudioCaptioning text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class objectiveType
    {

        public objectiveType()
        {
            this.status = lessonStatusType.not_attempted;
            this.score = new scoreType();

        }
        private string identifierField;

        private scoreType scoreField;

        private lessonStatusType statusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        [Priority(0)]
        public string id
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        [ScormSerialization.WriteOnly]
        public scoreType score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        public lessonStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum lessonStatusType
    {

        not_set,
        /// <remarks/>
        passed,

        failed,

        /// <remarks/>
        completed,

        /// <remarks/>
        incomplete,

        /// <remarks/>
        browsed,

        not_attempted
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseType
    {


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponseFillIn : studentResponseType
    {
        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponseMatching : studentResponseType
    {

        private System.Collections.Generic.List<studentResponseTypeStudentResponseMatchingMatch> matchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public System.Collections.Generic.List<studentResponseTypeStudentResponseMatchingMatch> match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponseMatchingMatch : studentResponseType
    {
        private string sourceField;

        private string targetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponseMultipleChoice : studentResponseType
    {

        private System.Collections.Generic.List<string> choiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("choice", DataType = "anyURI")]
        public System.Collections.Generic.List<string> choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponsePerformance : studentResponseType
    {

        private string stepNameField;

        private studentResponseTypeStudentResponsePerformanceStepAnswer stepAnswerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string stepName
        {
            get
            {
                return this.stepNameField;
            }
            set
            {
                this.stepNameField = value;
            }
        }

        /// <remarks/>
        public studentResponseTypeStudentResponsePerformanceStepAnswer stepAnswer
        {
            get
            {
                return this.stepAnswerField;
            }
            set
            {
                this.stepAnswerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponsePerformanceStepAnswer : studentResponseType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("literal", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("numeric", typeof(decimal))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class studentResponseTypeStudentResponseSequencing : studentResponseType
    {

        private System.Collections.Generic.List<string> stepField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step", DataType = "anyURI")]
        public System.Collections.Generic.List<string> step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {
        not_set,
        /// <remarks/>
        studentResponseFillIn,

        /// <remarks/>
        studentResponseLikert,

        /// <remarks/>
        studentResponseMatching,

        /// <remarks/>
        studentResponseMultipleChoice,

        /// <remarks/>
        studentResponseNumeric,

        /// <remarks/>
        studentResponsePerformance,

        /// <remarks/>
        studentResponseSequencing,

        /// <remarks/>
        studentResponseTrueFalse,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesType
    {
        public correctResponsesType()
        {
            this.Items = new System.Collections.Generic.List<object>();
            this.ItemsElementName = new System.Collections.Generic.List<ItemsChoiceType>();

        }
        private System.Collections.Generic.List<object> itemsField;

        private System.Collections.Generic.List<ItemsChoiceType> itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("correctResponseFillIn", typeof(correctResponsesTypeCorrectResponseFillIn))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseLikert", typeof(string), DataType = "anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseMatching", typeof(correctResponsesTypeCorrectResponseMatching))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseMultipleChoice", typeof(correctResponsesTypeCorrectResponseMultipleChoice))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseNumeric", typeof(correctResponsesTypeCorrectResponseNumeric))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponsePerformance", typeof(correctResponsesTypeCorrectResponsePerformance))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseSequencing", typeof(correctResponsesTypeCorrectResponseSequencing))]
        [System.Xml.Serialization.XmlElementAttribute("correctResponseTrueFalse", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<ItemsChoiceType> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseFillIn
    {

        private System.Collections.Generic.List<correctResponsesTypeCorrectResponseFillInMatchText> matchTextField;

        private bool caseMattersField;

        private bool orderMattersField;

        public correctResponsesTypeCorrectResponseFillIn()
        {
            this.caseMattersField = false;
            this.orderMattersField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("matchText")]
        public System.Collections.Generic.List<correctResponsesTypeCorrectResponseFillInMatchText> matchText
        {
            get
            {
                return this.matchTextField;
            }
            set
            {
                this.matchTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool caseMatters
        {
            get
            {
                return this.caseMattersField;
            }
            set
            {
                this.caseMattersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool orderMatters
        {
            get
            {
                return this.orderMattersField;
            }
            set
            {
                this.orderMattersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseFillInMatchText
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseMatching
    {

        private System.Collections.Generic.List<correctResponsesTypeCorrectResponseMatchingMatch> matchField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public System.Collections.Generic.List<correctResponsesTypeCorrectResponseMatchingMatch> match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseMatchingMatch
    {

        private string sourceField;

        private string targetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseMultipleChoice
    {

        private System.Collections.Generic.List<string> choiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("choice", DataType = "anyURI")]
        public System.Collections.Generic.List<string> choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseNumeric
    {

        private decimal minField;

        private decimal maxField;

        /// <remarks/>
        public decimal min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        public decimal max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformance
    {

        private System.Collections.Generic.List<correctResponsesTypeCorrectResponsePerformanceStep> stepField;

        private bool orderMattersField;

        public correctResponsesTypeCorrectResponsePerformance()
        {
            this.orderMattersField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step")]
        public System.Collections.Generic.List<correctResponsesTypeCorrectResponsePerformanceStep> step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool orderMatters
        {
            get
            {
                return this.orderMattersField;
            }
            set
            {
                this.orderMattersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformanceStep
    {

        private string stepNameField;

        private correctResponsesTypeCorrectResponsePerformanceStepStepAnswer stepAnswerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string stepName
        {
            get
            {
                return this.stepNameField;
            }
            set
            {
                this.stepNameField = value;
            }
        }

        /// <remarks/>
        public correctResponsesTypeCorrectResponsePerformanceStepStepAnswer stepAnswer
        {
            get
            {
                return this.stepAnswerField;
            }
            set
            {
                this.stepAnswerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformanceStepStepAnswer
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("literal", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("numeric", typeof(correctResponsesTypeCorrectResponsePerformanceStepStepAnswerNumeric))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponsePerformanceStepStepAnswerNumeric
    {

        private decimal minField;

        private decimal maxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class correctResponsesTypeCorrectResponseSequencing
    {

        private System.Collections.Generic.List<string> stepField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("step", DataType = "anyURI")]
        public System.Collections.Generic.List<string> step
        {
            get
            {
                return this.stepField;
            }
            set
            {
                this.stepField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        not_set,
        /// <remarks/>
        correctResponseFillIn,

        /// <remarks/>
        correctResponseLikert,

        /// <remarks/>
        correctResponseMatching,

        /// <remarks/>
        correctResponseMultipleChoice,

        /// <remarks/>
        correctResponseNumeric,

        /// <remarks/>
        correctResponsePerformance,

        /// <remarks/>
        correctResponseSequencing,

        /// <remarks/>
        correctResponseTrueFalse,
    }
    public class objectiveIDType
    {
        public objectiveIDType()
        {
            id = "";
        }
        public objectiveIDType(string i)
        {
            id = i;
        }
        private string _id;


        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public partial class interactionType
    {

        public interactionType()
        {
            this.correct_responses = new correctResponsesType();
            this.student_response = new studentResponseType();
            this.objectives = new System.Collections.Generic.List<objectiveIDType>();
            this.time = new Scorm1_2.DateTime(System.DateTime.Now);
            this.type = interactionTypeType.not_set;
            this.attemptNumberField = 1;
        }

        private string identifierField;

        private interactionTypeType typeField;

        private System.Collections.Generic.List<objectiveIDType> objectivesField;

        private Scorm1_2.DateTime timeField;

        private correctResponsesType correctResponsesField;

        private System.Nullable<decimal> weightingField;

        private studentResponseType studentResponseField;

        private interactionTypeResult resultField;

        private System.Nullable<decimal> resultNumericField;

        private string latencyField;
      
        private int attemptNumberField;



        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        [Priority(0)]
        public string id
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        [Priority(1)]
        /// <remarks/>
        public interactionTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objectiveId", DataType = "anyURI", IsNullable = false)]
        public System.Collections.Generic.List<objectiveIDType> objectives
        {
            get
            {
                return this.objectivesField;
            }
            set
            {
                this.objectivesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Scorm1_2.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        public correctResponsesType correct_responses
        {
            get
            {
                return this.correctResponsesField;
            }
            set
            {
                this.correctResponsesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> weighting
        {
            get
            {
                return this.weightingField;
            }
            set
            {
                this.weightingField = value;
            }
        }

        /// <remarks/>
        public studentResponseType student_response
        {
            get
            {
                return this.studentResponseField;
            }
            set
            {
                this.studentResponseField = value;
            }
        }

        /// <remarks/>
        public interactionTypeResult result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string latency
        {
            get
            {
                return this.latencyField;
            }
            set
            {
                this.latencyField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(1)]
        [ScormSerialization.Ignore]
        public int attemptNumber
        {
            get
            {
                return this.attemptNumberField;
            }
            set
            {
                this.attemptNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum interactionTypeType
    {
        not_set,
        /// <remarks/>
        true_false,

        /// <remarks/>
        multiple_choice,

        /// <remarks/>
        fill_in,

        /// <remarks/>
        likert,

        /// <remarks/>
        matching,

        /// <remarks/>
        performance,

        /// <remarks/>
        sequencing,

        /// <remarks/>
        numeric,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum interactionTypeResult
    {
        not_set,
        /// <remarks/>
        correct,

        /// <remarks/>
        wrong,

        /// <remarks/>
        neutral,

        /// <remarks/>
        unanticipated,
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum credit
    {
        not_set,
        /// <remarks/>
        credit,

        /// <remarks/>
        no_credit,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum entry
    {
        not_set,
        /// <remarks/>
        ab_initio,

        /// <remarks/>
        resume,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum exit
    {
        not_set,
        /// <remarks/>
        logout,

        /// <remarks/>
        blank,

        /// <remarks/>
        suspend,

        /// <remarks/>
        time_out,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum learnerPreferenceAudioCaptioning
    {
        not_set,
        /// <remarks/>
        off,

        /// <remarks/>
        no_change,

        /// <remarks/>
        on,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum mode
    {
        not_set,
        /// <remarks/>
        browse,

        /// <remarks/>
        normal,

        /// <remarks/>
        review,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/1484_11_3")]
    public enum timeLimitAction
    {
        not_set,
        /// <remarks/>
        continue_message,

        /// <remarks/>
        continue_no_message,

        /// <remarks/>
        exit_message,

        /// <remarks/>
        exit_no_message,
    }

  
}